[package]
name = "hotux"
version = "0.1.0"
description = "A system resource monitor that shows the state of your 'Linux' system. "
authors = ["nixtrim <omuaz01@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
